import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Terminal Authority Color Palette
        'tertiary-fixed': '#5e5e67',
        'secondary': '#c6c6c7',
        'on-primary-fixed': '#ffffff',
        'on-secondary-fixed-variant': '#3a3c3c',
        'tertiary': '#e3e1ec',
        'tertiary-fixed-dim': '#46464f',
        'inverse-primary': '#596400',
        'on-error-container': '#ffdad6',
        'surface-dim': '#131315',
        'on-primary-container': '#000000',
        'outline-variant': '#474747',
        'error': '#ffb4ab',
        'tertiary-container': '#90909a',
        'primary': '#ffffff',
        'primary-container': '#cae025',
        'on-secondary': '#1a1c1c',
        'surface-container': '#201f22',
        'primary-fixed': '#596400',
        'on-surface': '#e5e1e4',
        'on-tertiary-container': '#000000',
        'background': '#08080A',
        'error-container': '#93000a',
        'surface': '#131315',
        'on-surface-variant': '#c6c6c6',
        'surface-tint': '#bcd20e',
        'secondary-container': '#454747',
        'inverse-on-surface': '#313032',
        'on-tertiary-fixed-variant': '#e3e1ec',
        'primary-fixed-dim': '#434b00',
        'on-secondary-container': '#e2e2e2',
        'on-background': '#e5e1e4',
        'inverse-surface': '#e5e1e4',
        'surface-variant': '#353437',
        'surface-bright': '#39393b',
        'on-tertiary': '#1a1b23',
        'on-primary-fixed-variant': '#d8ee36',
        'on-tertiary-fixed': '#ffffff',
        'secondary-fixed-dim': '#aaabab',
        'surface-container-high': '#2a2a2c',
        'surface-container-low': '#1c1b1e',
        'on-error': '#690005',
        'on-primary': '#191e00',
        'surface-container-highest': '#353437',
        'surface-container-lowest': '#0e0e10',
        'outline': '#919191',
        'secondary-fixed': '#c6c6c7',
        'on-secondary-fixed': '#1a1c1c',
        'lime-accent': '#E8FF47',
        // Custom colors for your spec
        'test': '#52525B',
        'neutral': '#08080A',
      },
      borderRadius: {
        'DEFAULT': '0px',
        'sm': '0px',
        'md': '2px',
        'lg': '2px',
        'xl': '2px',
        'full': '0px',
      },
      fontFamily: {
        'headline': ['Inter', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      letterSpacing: {
        'tight': '-0.02em',
        'tighter': '-0.04em',
      },
    },
  },
  plugins: [],
};
export default config;
