-- Seed skills data with predefined skills
INSERT INTO public.skills (name, category) VALUES
-- Frontend
('React', 'Frontend'),
('Vue', 'Frontend'),
('Angular', 'Frontend'),
('Next.js', 'Frontend'),
('TypeScript', 'Frontend'),
('JavaScript', 'Frontend'),
('TailwindCSS', 'Frontend'),
('CSS', 'Frontend'),
('HTML', 'Frontend'),
('SASS', 'Frontend'),
('Redux', 'Frontend'),
('Zustand', 'Frontend'),
('Webpack', 'Frontend'),
('Vite', 'Frontend'),
('Framer Motion', 'Frontend'),
('Three.js', 'Frontend'),
('D3.js', 'Frontend'),
('Storybook', 'Frontend'),
('Jest', 'Frontend'),
('Cypress', 'Frontend'),
-- Backend
('Node.js', 'Backend'),
('Python', 'Backend'),
('Go', 'Backend'),
('Rust', 'Backend'),
('Java', 'Backend'),
('C#', 'Backend'),
('PHP', 'Backend'),
('Ruby', 'Backend'),
('Express', 'Backend'),
('FastAPI', 'Backend'),
('Django', 'Backend'),
('Flask', 'Backend'),
('Spring Boot', 'Backend'),
('NestJS', 'Backend'),
('GraphQL', 'Backend'),
('REST APIs', 'Backend'),
('gRPC', 'Backend'),
-- Databases
('PostgreSQL', 'Databases'),
('MySQL', 'Databases'),
('MongoDB', 'Databases'),
('Redis', 'Databases'),
('SQLite', 'Databases'),
('Elasticsearch', 'Databases'),
('Prisma', 'Databases'),
('Sequelize', 'Databases'),
('TypeORM', 'Databases'),
-- DevOps
('Docker', 'DevOps'),
('Kubernetes', 'DevOps'),
('AWS', 'DevOps'),
('GCP', 'DevOps'),
('Azure', 'DevOps'),
('CI/CD', 'DevOps'),
('GitHub Actions', 'DevOps'),
('GitLab CI', 'DevOps'),
('Terraform', 'DevOps'),
('Ansible', 'DevOps'),
('Linux', 'DevOps'),
('Bash', 'DevOps'),
('Nginx', 'DevOps'),
-- Mobile
('React Native', 'Mobile'),
('Flutter', 'Mobile'),
('Swift', 'Mobile'),
('Kotlin', 'Mobile'),
('iOS', 'Mobile'),
('Android', 'Mobile'),
-- Other
('Git', 'Other'),
('Testing', 'Other'),
('Security', 'Other'),
('Performance', 'Other'),
('Accessibility', 'Other'),
('UI/UX', 'Other'),
('Agile', 'Other'),
('Scrum', 'Other'),
('System Design', 'Other'),
('Microservices', 'Other')
ON CONFLICT (name) DO NOTHING;
